import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

// export const metadata = {
//   title: "farhan-PIAIC",
//   description: "Generated by create next app",
  
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>PIAIC-farhan</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/titleLogo.png" />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
